### PR TITLE
DDCE-4709 Upgrade RAS to Upscan

### PR DESCRIPTION
**Pull request by zmdnoor**

### CODE REVIEW

**Review by MRBeresford — CHANGES_REQUESTED** [review]
Few comments, let me know if you want to go through them etc :)

**Comment by MRBeresford** [comment]
There is also this PR bot comment
`uk.gov.hmrc.sbt-auto-build can be updated to 3.21.0 in [project/plugins.sbt](https://github.com/hmrc/ras-api/blob/DDCE-4709/project/plugins.sbt#L8)`

**Comment by zmdnoor** [comment]
Changes implemented, have a look and let me know :)

**Review by MRBeresford — APPROVED** [review]
LGTM

**Pull request merged**
